### ISSUE TITLE
Update unit tests to match ref spec Version2VectorTest

### ISSUE THREAD

**Issue by rlittlefield** [rlittlefield/pypaseto#7]
Update unit tests to match ref spec Version2VectorTest.

They were recently updated in the php reference implementation to include corrected exp dated (with trailing '+00:00'. We should update our tests to match to avoid any divergence.

**Comment by mjpieters** [comment]
The tests are a bit more behind than just updating the expiration date. I believe that [this is the range of changes](https://github.com/paragonie/paseto/compare/30ee26dfbc6389804bceca91a60661ba57c6d4b9...a37b5a889e33cda2d923e880962ccc6fe3b449b8#diff-2e409a902f2fc8c486f612125b069c3b) that also need to be applied to include the expiration date changes.

Since that change, there have been [further updates to the test suite](https://github.com/paragonie/paseto/compare/a37b5a889e33cda2d923e880962ccc6fe3b449b8...master#diff-2e409a902f2fc8c486f612125b069c3b) that probably should be taken into account.
